### ISSUE TITLE
how to know mouse click in desktop

### ISSUE THREAD

**Issue by ddatsh** [moutend/go-hook#1]
as title

**Comment by florianjs** [comment]
As mentioned here https://github.com/moutend/go-hook/blob/master/mouse/mouse_windows_amd64.go#L17 and here https://docs.microsoft.com/en-us/previous-versions/dd162805(v=vs.85) , you can use hook.POINT to define the current coordinates of the mouse.

**Comment by moutend** [comment]
@ddatsh I'm sorry that take a long time to reply.

Now, I released go-hook v0.1.0, and it supports mouse events. Try the code located in `examples/mouse`.

**Comment by ddatsh** [comment]
> @ddatsh I'm sorry that take a long time to reply.
> 
> Now, I released go-hook v0.1.0, and it supports mouse events. Try the code located in `examples/mouse`.

my description not correct,  I want to know mouse click in my desktop area, not from other place, like in chrome..
